### ISSUE TITLE
[ISSUE] Error when checking if shops are loaded.

### ISSUE THREAD

**Issue by ItzSave** [BG-Software-LLC/ShopsBridge#3]
I have reset the configuration file for ShopGUIPlus and this error still appears when using the API.

It's like that this could be a problem with my implementation.
```[23:42:43 ERROR]: Could not pass event ItemSpawnEvent to ZithiumCollectors v2.0.6-BETA
java.lang.NullPointerException: Cannot invoke "net.brcdev.shopgui.gui.element.button.GuiButton.getItemStack()" because "net.brcdev.shopgui.config.Settings.buttonGoBack" is null
        at net.brcdev.shopgui.shop.ShopManager.loadShop(ShopManager.java:210) ~[ShopGUIPlus-1.95.0.jar:?]
        at net.brcdev.shopgui.shop.ShopManager.loadShops(ShopManager.java:130) ~[ShopGUIPlus-1.95.0.jar:?]
        at net.brcdev.shopgui.shop.ShopManager.load(ShopManager.java:83) ~[ShopGUIPlus-1.95.0.jar:?]
        at net.zithium.collectors.libs.shopsbridge.ShopsBridge_ShopGUIPlus1_80.ensureShopsLoaded(ShopsBridge_ShopGUIPlus1_80.java:78) ~[ZithiumCollectors-2.0.6-BETA.jar:?]
        at net.zithium.collectors.libs.shopsbridge.ShopsBridge_ShopGUIPlus1_80.getSellPrice(ShopsBridge_ShopGUIPlus1_80.java:36) ~[ZithiumCollectors-2.0.6-BETA.jar:?]
        at net.zithium.collectors.price.impl.ShopsBridgeProvider.getPriceForItem(ShopsBridgeProvider.java:20) ~[ZithiumCollectors-2.0.6-BETA.jar:?]
        at net.zithium.collectors.price.ShopManager.getItemPrice(ShopManager.java:58) ~[ZithiumCollectors-2.0.6-BETA.jar:?]
        at net.zithium.collectors.collector.ChunkCollector.calculateTotalWorth(ChunkCollector.java:205) ~[ZithiumCollectors-2.0.6-BETA.jar:?]
        at net.zithium.collectors.collector.ChunkCollector.addCollectionItem(ChunkCollector.java:113) ~[ZithiumCollectors-2.0.6-BETA.jar:?]
        at net.zithium.collectors.collector.CollectorManager.modifyCollectorItemAmount(CollectorManager.java:363) ~[ZithiumCollectors-2.0.6-BETA.jar:?]
        at net.zithium.collectors.listener.EntitySpawnListener.onEntitySpawn(EntitySpawnListener.java:30) ~[ZithiumCollectors-2.0.6-BETA.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1167.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:git-Pufferfish-73]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:785) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:666) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1530) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1438) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.dropItem(CraftWorld.java:706) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at org.bukkit.craftbukkit.v1_19_R3.CraftWorld.dropItem(CraftWorld.java:695) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:911) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1764) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1661) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1488) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.pushEntities(LivingEntity.java:3513) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3416) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:672) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
        at net.minecraft.world.entity.monster.AbstractSkeleton.aiStep(AbstractSkeleton.java:131) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2997) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:434) ~[?:?]
        at net.minecraft.world.entity.monster.Skeleton.tick(Skeleton.java:69) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1226) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:734) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1548) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1176) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]```

**Comment by OmerBenGera** [comment]
You had a case when you tried to get prices of an item before the shops were loaded by SGP.
ShopsBridge then called ShopManager#load, which then threw the error.

I suspect it happened because of a faulty configuration or something, as it fails to find the 'go back' button, and this might have been the reason why the shops weren't loaded in first place.

**Comment by OmerBenGera** [comment]
Is this still relevant?
